# Generated by Django 3.2.5 on 2021-07-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_header',
            new_name='post_header',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_img',
            new_name='post_img',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='post_text',
        ),
    ]
